#!/bin/sh

for pkg in `ls .`; do
  if [ $pkg != `basename $0` ] && ! `dpkg -s $pkg > /dev/null 2>&1`; then
    PACKAGES="$PACKAGES $pkg"
  fi
done

if [ -n "$PACKAGES" ]; then
  echo "$ su -c apt-get install $PACKAGES"
  su -c "apt-get install $PACKAGES"
fi
