#!/bin/sh

for pkg in `ls .`; do
  if [ $pkg != 'deploy' ] && [ ! `dpkg -s $pkg > /dev/null 2>&1` ]; then
    PACKAGES="$PACKAGES $pkg"
  fi
done

if [ -n "$PACKAGES" ]; then
  echo "$ su -c apt-get install $PACKAGES"
  su -c "apt-get install $PACKAGES"
fi
